
server:
  port: 9999

spring:
  application:
    name: config-center
  cloud:
    config:
      server:
        git:
          uri: 
          search-paths:
          - config-repo
          username: 
          password: 
          basedir:
          force-pull: true
          
  rabbitmq:
    host: 192.168.153.131
    port: 5672
    username: admin
    password: 123456
          
eureka:
  client:
    service-url:
      defaultZone: http://admin:admin@localhost:8763/eureka/
      
encrypt:
  key-store:
    location: 
    alias: 
    password: 
    secret: 
    
management:
  endpoints:
    web:
      exposure:
        include: "*"
